---
- name: Users | Groups | Additing new groups to remote system
  group: 
    name:   "{{ item.name }}"
    system: "{{ item.system|default(false)|bool }}"
    state:  "present"
    gid:    "{{ item.gid|default(omit) }}"
  with_items: "{{ users_add_groups }}"

- name: Users | Groups | Removing groups from remote system
  group: 
    name:   "{{ item.name }}"
    system: "{{ item.system|default(false)|bool }}"
    state:  "absent"
    gid:    "{{ item.gid|default(omit) }}"
  with_items: "{{ users_remove_groups }}"
