- name: Users | Keys | Removing current keys file
  file:
    path:     "/home/{{ item.name }}/.ssh/authorized_keys"
    state:    absent
  with_items: "{{ users_add_users }}"
  when: "{{ users_remove_authorized_keys }}"

- name: Users | Keys | Creating remote SSH keys for user
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1}}"
    exclusive: no
  with_subelements:
    - "{{ users_add_users }}"
    - keys
    - "{{ users_loop_flags }}"
