---
- include: sshd.yml
  when: "{{ users_sshd_config }} == True"

- include: sftp.yml
  when: "{{ users_sftp_enabled }} == True
  and {{ users_sshd_config }} == True"

- include: groups.yml

- include: users.yml

- include: keys.yml

