---
- include_tasks: sshd.yml
  when:
    - users_sshd_config == True

- include_tasks: sftp.yml
  when:
    - users_sftp_enabled == True
    - users_sshd_config == True

- include_tasks: groups.yml

- include_tasks: users.yml

- include_tasks: keys.yml
