---
- include_vars: "os_{{ ansible_os_family }}.yml"

- name: Users | SSHD | Configuring SSHD
  template:
    src: sshd_config.j2
    dest: "{{ sshd_config_file }}"
    backup: yes
  notify: "Users | Handlers | Restart SSHD"
