- name: Users | Accounts | Removing accounts from remote system
  user:
    name:   "{{ item.name }}"
    state:  "absent"
    force:  "yes"
    remove: "remove"
    uid:    "{{ item.uid|default(omit) }}"
  with_items: "{{ users_remove_users }}"

- name: Users | Accounts | Creating accounts on remote system
  user:
    name:               "{{ item.name }}"
    password:           "{{ item.password|default(omit) }}"
    createhome:         "{{ item.createhome|default(users_add_users_default_createhome) }}"
    home:               "{{ item.home|default(omit) }}"
    system:             "{{ item.system|default(users_add_users_default_system) }}"
    group:              "{{ item.group|default(omit) }}"
    groups:             "{{ item.groups|default(users_add_users_default_groups)|join(',') }}"
    state:              "present"
    shell:              "{{ item.shell|default(users_add_users_default_shell) }}"
    uid:                "{{ item.uid|default(omit) }}"
    comment:            "{{ item.comment|default(omit) }}"
    append:             "{{ item.append|default(users_add_users_default_append) }}"
    expires:            "{{ item.expires|default(omit) }}"
    generate_ssh_key:   "{{ item.generate_ssh_key|default(users_add_users_default_generate_ssh_key) }}"
    move_home:          "{{ item.move_home|default(users_add_users_default_move_home) }}"
    non_unique:         "{{ item.non_unique|default(omit) }}"
    seuser:             "{{ item.seuser|default(omit) }}"
    skeleton:           "{{ item.skeleton|default(omit) }}"
    ssh_key_bits:       "{{ item.ssh_key_bits|default(users_add_users_default_ssh_key_bits) }}"
    ssh_key_comment:    "{{ item.ssh_key_comment|default(users_add_users_default_ssh_key_comment) }}"
    ssh_key_file:       "{{ item.ssh_key_file|default(users_add_users_default_ssh_key_file) }}"
    ssh_key_passphrase: "{{ item.ssh_key_passphrase|default(users_add_users_default_ssh_key_passphrase) }}"
    ssh_key_type:       "{{ item.ssh_key_type|default(users_add_users_default_ssh_key_type) }}"
    update_password:    "{{ item.update_password|default(users_add_users_default_update_password) }}"
  with_items: "{{ users_add_users }}"

